### ISSUE TITLE
Having just one bot does not work?

### ISSUE THREAD

**Issue by Cr4xy** [gegy1000/AgarBot#1]
Stacktrace:
```
Exception in thread "Thread-3" java.lang.ArrayIndexOutOfBoundsException: 0
	at com.pau101.neural.NeuralNet.getNode(NeuralNet.java:29)
	at net.gegy1000.agarbot.PlayerController.evaluate(PlayerController.java:286)
	at net.gegy1000.agarbot.PlayerController.tick(PlayerController.java:363)
	at net.gegy1000.agarbot.Game.controlUpdate(Game.java:88)
	at net.gegy1000.agarbot.Main$1.run(Main.java:85)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by gegy1000** [comment]
Reset your neural net file in <workspacedir>/net/neural_net.nnet :)

**Comment by Cr4xy** [comment]
Ah ok, thank you! :)
You should maybe make the net folder or create it in the code :) It fails when the folder does not exist.

**Comment by gegy1000** [comment]
Okay, didn't know that was happening, I'll fix that soon! :) Thanks for the notification.
